name: Deploy to DigitalOcean Droplet

on:
  push:
    branches:
      - main  # Trigger on merge to main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.8.1
        with:
          ssh-private-key: ${{ secrets.DO_SSH_KEY }}

      - name: Deploy to DigitalOcean
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.DO_SSH_USER }}@${{ secrets.DO_SSH_IP }} << EOF
            cd Adob-Kft
            git pull origin main
            docker-compose -f docker-compose.prod.yml down
            docker-compose -f docker-compose.prod.yml up -d --build

            # Install PHP dependencies
            docker-compose -f docker-compose.prod.yml exec app composer install --no-interaction --prefer-dist

            # Start Laravel Horizon
            docker-compose -f docker-compose.prod.yml exec app php artisan horizon
          EOF
